echo "广东电信,#genre#" >zubo2.txt
cat txt/广东电信.txt >>zubo2.txt
echo "\n北京联通,#genre#" >>zubo2.txt
cat txt/北京联通.txt >>zubo2.txt
echo "\n湖北电信,#genre#" >>zubo2.txt
cat txt/湖北电信.txt >>zubo2.txt
echo "\n浙江电信,#genre#" >>zubo2.txt
cat txt/浙江电信.txt >>zubo2.txt
echo "\n广东联通,#genre#" >>zubo2.txt
cat txt/广东联通.txt >>zubo2.txt
echo "\n江苏电信,#genre#" >>zubo2.txt
cat txt/江苏电信.txt >>zubo2.txt
#echo "\n湖南电信,#genre#" >>zubo2.txt
#cat txt/湖南电信.txt >>zubo2.txt