cat 广东电信.txt >zubo.txt
cat 北京联通.txt >>zubo.txt
cat 湖南电信.txt >>zubo.txt
cat 广东联通.txt >>zubo.txt
echo "湖北电信-组播,#genre#" >>zubo.txt
cat txt/湖北电信.txt >>zubo.txt
echo "浙江电信-组播,#genre#" >>zubo.txt
cat txt/浙江电信.txt >>zubo.txt
echo "江苏电信-组播,#genre#" >>zubo.txt
cat txt/江苏电信.txt >>zubo.txt