cat txt/广东电信.txt >zubo.txt
cat txt/北京联通.txt >>zubo.txt
cat txt/广东联通.txt >>zubo.txt
#cat txt/湖南电信.txt >>zubo.txt
echo "湖北电信_组播,#genre#" >>zubo.txt
cat txt/湖北电信.txt >>zubo.txt
echo "浙江电信_组播,#genre#" >>zubo.txt
cat txt/浙江电信.txt >>zubo.txt
echo "江苏电信_组播,#genre#" >>zubo.txt
cat txt/江苏电信.txt >>zubo.txt
